### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ProjectSynchro** [ProjectSynchro/com.artemis_rgb.Artemis#1]
Moved this from my local notes to Github.

- [x] Create Flatpak manifest file.
- [x] Figure out how to do .NET dependency management
- [x] Get Artemis building in Flatpak with manual steps to get a working list of dependencies
- [x] Create a build script to simplify the Flatpak manifest.
- [x] Automate the creation of nuget sources with `flatpak-dotnet-generator.py`
- [x] Create Metainfo, desktop file
   - [x] Verify we meet [Metainfo guidelines](https://github.com/flathub/flathub/wiki/AppData-Guidelines) (solved as of https://github.com/ProjectSynchro/com.artemis_rgb.Artemis/commit/ca18b46cda08164ceb851fbb283a0ce2c82299f6)
- [ ] Fix automated dependency updates
- [ ] Document stuff

**Comment by ProjectSynchro** [comment]
Still outstanding: 
- [x] Fix issues related to the Wooting Analog Plugin (#4)
- [x] #2 (Solved as of 71c335fb39a39f9c47abc50deb4a67786aa0d003)
- [ ] Get onto Flathub!
   - [ ] [App Requirements Met](https://github.com/flathub/flathub/wiki/App-Requirements)
   - [ ] [App Submission Created](https://github.com/flathub/flathub/wiki/App-Submission)

**Comment by mrdev023** [comment]
Any news about Flathub availability ?
